// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2sA_2RhXxyQ0CLcyvR75CrWGKZW8VDl8',
    appId: '1:1013286477109:web:bfb751c36eea349a69807c',
    messagingSenderId: '1013286477109',
    projectId: 'the-sanity-line',
    authDomain: 'the-sanity-line.firebaseapp.com',
    storageBucket: 'the-sanity-line.firebasestorage.app',
    measurementId: 'G-FE8QL6N9NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYsiDd4ChXk6x37-l0woSskvguSgX9Lq4',
    appId: '1:1013286477109:android:6aaff48185b3f20969807c',
    messagingSenderId: '1013286477109',
    projectId: 'the-sanity-line',
    storageBucket: 'the-sanity-line.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC20V9rKhyhFb_6qJyiqEyT6VdVrLLFPRA',
    appId: '1:1013286477109:ios:ef3bef3b7eac7aca69807c',
    messagingSenderId: '1013286477109',
    projectId: 'the-sanity-line',
    storageBucket: 'the-sanity-line.firebasestorage.app',
    iosBundleId: 'com.example.theSanityLine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC20V9rKhyhFb_6qJyiqEyT6VdVrLLFPRA',
    appId: '1:1013286477109:ios:ef3bef3b7eac7aca69807c',
    messagingSenderId: '1013286477109',
    projectId: 'the-sanity-line',
    storageBucket: 'the-sanity-line.firebasestorage.app',
    iosBundleId: 'com.example.theSanityLine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2sA_2RhXxyQ0CLcyvR75CrWGKZW8VDl8',
    appId: '1:1013286477109:web:0ac96778cfd198bc69807c',
    messagingSenderId: '1013286477109',
    projectId: 'the-sanity-line',
    authDomain: 'the-sanity-line.firebaseapp.com',
    storageBucket: 'the-sanity-line.firebasestorage.app',
    measurementId: 'G-S0T7XBKN7B',
  );
}
